import type { Timestamp } from './common'

// ─── push tokens (contacts/{contactId}/push_tokens/{token}) ───────────────────
//
// Server-half of push notifications ONLY — see docs/mobile-roadmap-2026-09.md
// (or its successor) for the client half, which lands separately. Nothing in
// this codebase sends a notification off this collection yet; it exists so
// the mobile app's future `expo-notifications` registration has somewhere
// idempotent to write.
//
// THE DOC ID IS THE TOKEN, and that is the whole idempotency story: a device
// re-registers on every foreground/permission change (and an Expo push token
// can itself rotate), so a `set()` on an id derived from the token is a
// self-correcting upsert — refresh `last_seen_at`, never spawn a second row
// for the same device. Two alternatives were rejected for the same reason:
// keying by contact+platform cannot express "this phone got a new token"
// without either orphaning the old row or a query-then-write race, and an
// autogenerated id would accumulate a duplicate every re-registration — which
// is exactly the rot the pruning step in `sendPush`
// (packages/functions/src/push/sendPush.ts) exists to undo once a token goes
// dead (unregistered/invalid) rather than merely stale.
//
// `token` duplicates the doc id as a field for the same reason `PlanPurchase`
// and `CreditGrant` do (packages/shared/src/types/contact.ts): a caller
// iterating a query result reads it off the row without re-deriving it from
// `doc.id`.
export type PushTokenKind = 'expo' | 'fcm'
export type PushPlatform = 'ios' | 'android'

export interface PushToken {
  /** Same value as the doc id. */
  token: string
  teamId: string
  /** Which delivery vendor this token addresses — see
   *  packages/functions/src/push/provider.ts, the ONE place that's decided. */
  kind: PushTokenKind
  platform: PushPlatform
  /** App version the client registered under (e.g. from `expo-application`). */
  app_version?: string | null
  /** Expo Updates runtime version the client registered under, when known —
   *  same field this is named after on `MobileAppTelemetry` (types/contact.ts). */
  runtime_version?: string | null
  created_at: Timestamp
  /** Refreshed by the client on every (re)registration. The only OTHER writer
   *  is `sendPush`'s pruning step, and it only ever DELETES a dead token — it
   *  never bumps this field. */
  last_seen_at: Timestamp
}
