#!/usr/bin/env bash
# Provisions a Codespace / dev container for dgstn-lineup.
# Runs once, as the devcontainer postCreateCommand.
set -euo pipefail

echo "==> Enabling pnpm via corepack"
corepack enable
corepack prepare pnpm@9.15.0 --activate

echo "==> Installing firebase-tools (emulator CLI)"
npm install -g firebase-tools

echo "==> Installing workspace dependencies"
pnpm install

echo "==> Writing apps/web/.env.local (emulator mode)"
if [ ! -f apps/web/.env.local ]; then
  cat > apps/web/.env.local <<'EOF'
# Auto-generated by .devcontainer/setup.sh — points the web app at the
# local Firebase emulators (demo-lineup project). Safe placeholder values.
NEXT_PUBLIC_USE_EMULATORS=true
NEXT_PUBLIC_FIREBASE_API_KEY=demo-api-key
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=demo-lineup.firebaseapp.com
NEXT_PUBLIC_FIREBASE_DATABASE_URL=https://demo-lineup.firebaseio.com
NEXT_PUBLIC_FIREBASE_PROJECT_ID=demo-lineup
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=demo-lineup.appspot.com
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=000000000000
NEXT_PUBLIC_FIREBASE_APP_ID=1:000000000000:web:0000000000000000000000
EOF
  echo "    created apps/web/.env.local"
else
  echo "    apps/web/.env.local already exists — left untouched"
fi

echo ""
echo "==> Setup complete."
echo "    Start everything with:  pnpm dev:codespace"
echo "    (Firebase emulators + seed data + Next.js dev server on port 3000)"
