#!/usr/bin/env bash
# Provisions a Codespace / dev container for dgstn-lineup.
# Runs once, as the devcontainer postCreateCommand.
set -euo pipefail

echo "==> Enabling pnpm via corepack"
corepack enable
corepack prepare pnpm@9.15.0 --activate

# Installs all workspace deps including firebase-tools (a root devDependency),
# so the `firebase` CLI is available to pnpm-invoked scripts via node_modules/.bin.
echo "==> Installing workspace dependencies"
pnpm install

echo "==> Writing apps/web/.env.local (emulator mode)"
# Auto-generated — points the web app at the local Firebase emulators
# (demo-lineup project). Safe placeholder values. Regenerated every build.
cat > apps/web/.env.local <<'EOF'
# Auto-generated by .devcontainer/setup.sh — do not edit by hand.
NEXT_PUBLIC_USE_EMULATORS=true
NEXT_PUBLIC_FIREBASE_API_KEY=demo-api-key
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=demo-lineup.firebaseapp.com
NEXT_PUBLIC_FIREBASE_DATABASE_URL=https://demo-lineup.firebaseio.com
NEXT_PUBLIC_FIREBASE_PROJECT_ID=demo-lineup
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=demo-lineup.appspot.com
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=000000000000
NEXT_PUBLIC_FIREBASE_APP_ID=1:000000000000:web:0000000000000000000000
EOF

# In a Codespace the emulators are reached via HTTPS port-forwarding, not
# localhost. Expose the codespace name + domain so the browser SDK can build
# the forwarded emulator URLs (<codespace>-<port>.<domain>).
if [ -n "${CODESPACE_NAME:-}" ] && [ -n "${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN:-}" ]; then
  {
    echo "NEXT_PUBLIC_CODESPACE_NAME=${CODESPACE_NAME}"
    echo "NEXT_PUBLIC_CODESPACE_DOMAIN=${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"
  } >> apps/web/.env.local
  echo "    created apps/web/.env.local (Codespaces mode)"
else
  echo "    created apps/web/.env.local (localhost mode)"
fi

echo ""
echo "==> Setup complete."
echo "    Start everything with:  pnpm dev:codespace"
echo "    (Firebase emulators + seed data + Next.js dev server on port 3000)"
