#!/usr/bin/env node
/**
 * Full local dev bootstrap for billing testing.
 * Identical to dev-local.mjs but also starts the Firebase Functions emulator
 * on :5001 so that callable functions (createCheckoutSession, etc.) run locally.
 *
 * Usage:
 *   1. Fill in STRIPE_SECRET_KEY and STRIPE_WEBHOOK_SECRET in packages/functions/.env.local
 *   2. pnpm dev:billing            (this script — in one terminal)
 *   3. pnpm stripe:listen          (in a second terminal, after emulators are up)
 *
 * Stripe CLI setup (one-time):
 *   https://docs.stripe.com/stripe-cli  →  stripe login
 *   The `stripe:listen` script auto-forwards test webhooks to the local function.
 */

import { spawn } from 'child_process'
import { createConnection } from 'net'
import { writeFileSync } from 'fs'
import { fileURLToPath } from 'url'
import { join, dirname } from 'path'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')

// ── .env.local ────────────────────────────────────────────────────────────────

const envPath = join(ROOT, 'apps', 'web', '.env.local')
writeFileSync(envPath, [
  '# Auto-generated by scripts/dev-billing.mjs — do not edit by hand.',
  'NEXT_PUBLIC_USE_EMULATORS=true',
  'NEXT_PUBLIC_FIREBASE_API_KEY=demo-api-key',
  'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=demo-lineup.firebaseapp.com',
  'NEXT_PUBLIC_FIREBASE_DATABASE_URL=https://demo-lineup.firebaseio.com',
  'NEXT_PUBLIC_FIREBASE_PROJECT_ID=demo-lineup',
  'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=demo-lineup.appspot.com',
  'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=000000000000',
  'NEXT_PUBLIC_FIREBASE_APP_ID=1:000000000000:web:0000000000000000000000',
].join('\n') + '\n')
console.log('==> Wrote apps/web/.env.local')

// ── helpers ───────────────────────────────────────────────────────────────────

function run(cmd, args, opts = {}) {
  return spawn(cmd, args, { stdio: 'inherit', shell: true, cwd: ROOT, ...opts })
}

function waitForPort(port, timeoutMs = 120_000) {
  return new Promise((resolve, reject) => {
    const deadline = Date.now() + timeoutMs
    function attempt() {
      const sock = createConnection(port, '127.0.0.1')
      sock.on('connect', () => { sock.destroy(); resolve() })
      sock.on('error', () => {
        sock.destroy()
        if (Date.now() > deadline) {
          reject(new Error(`Port ${port} not available after ${timeoutMs}ms`))
        } else {
          setTimeout(attempt, 1000)
        }
      })
    }
    attempt()
  })
}

function runToCompletion(cmd, args) {
  return new Promise((resolve) => {
    const p = run(cmd, args)
    p.on('exit', (code) => resolve(code ?? 0))
  })
}

// ── main ──────────────────────────────────────────────────────────────────────

console.log('==> Building Cloud Functions (required for functions emulator)…')
const buildCode = await runToCompletion('pnpm', ['--filter', '@lineup/functions', 'run', 'build'])
if (buildCode !== 0) {
  console.error('❌ Functions build failed — fix type errors before starting billing dev')
  process.exit(1)
}

console.log('==> Starting Firebase emulators (auth, firestore, functions)…')
const emulators = run('pnpm', ['exec', 'firebase', 'emulators:start',
  '--only', 'auth,firestore,functions', '--project', 'demo-lineup'])

function cleanup() {
  try { emulators.kill() } catch {}
}
process.on('exit', cleanup)
process.on('SIGINT', () => process.exit(0))
process.on('SIGTERM', () => process.exit(0))

console.log('==> Waiting for Firestore emulator on :8080')
await waitForPort(8080)
console.log('==> Waiting for Auth emulator on :9099')
await waitForPort(9099)
console.log('==> Waiting for Functions emulator on :5001')
await waitForPort(5001)
console.log('    emulators up')

console.log('==> Seeding emulator data')
const seedCode = await runToCompletion('pnpm', ['seed'])
if (seedCode !== 0) console.log('    seed failed (continuing anyway)')

console.log('')
console.log('  ┌──────────────────────────────────────────────────────────────────┐')
console.log('  │  Billing emulator ready. To test Stripe webhooks, run in a       │')
console.log('  │  second terminal:                                                 │')
console.log('  │                                                                   │')
console.log('  │    pnpm stripe:listen                                             │')
console.log('  │                                                                   │')
console.log('  │  Then copy the whsec_... secret into:                            │')
console.log('  │    packages/functions/.env.local → STRIPE_WEBHOOK_SECRET         │')
console.log('  │  and restart this script.                                         │')
console.log('  └──────────────────────────────────────────────────────────────────┘')
console.log('')

console.log('==> Starting Next.js dev server on :3000')
const web = run('pnpm', ['dev:web'])
web.on('exit', () => process.exit(0))
