#!/usr/bin/env node
/**
 * Cross-platform local dev bootstrap (replaces bash scripts/dev.sh for Windows).
 * Starts Firebase emulators, waits for them, seeds, then starts the web dev server.
 * Works on Windows (PowerShell / cmd), macOS, and Linux without any extra deps.
 */

import { spawn } from 'child_process'
import { createConnection } from 'net'
import { writeFileSync } from 'fs'
import { fileURLToPath } from 'url'
import { join, dirname } from 'path'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')

// ── .env.local ────────────────────────────────────────────────────────────────

const envPath = join(ROOT, 'apps', 'web', '.env.local')
writeFileSync(envPath, [
  '# Auto-generated by scripts/dev-local.mjs — do not edit by hand.',
  'NEXT_PUBLIC_USE_EMULATORS=true',
  'NEXT_PUBLIC_FIREBASE_API_KEY=demo-api-key',
  'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=demo-lineup.firebaseapp.com',
  'NEXT_PUBLIC_FIREBASE_DATABASE_URL=https://demo-lineup.firebaseio.com',
  'NEXT_PUBLIC_FIREBASE_PROJECT_ID=demo-lineup',
  'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=demo-lineup.appspot.com',
  'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=000000000000',
  'NEXT_PUBLIC_FIREBASE_APP_ID=1:000000000000:web:0000000000000000000000',
].join('\n') + '\n')
console.log('==> Wrote apps/web/.env.local')

// ── helpers ───────────────────────────────────────────────────────────────────

function run(cmd, args, opts = {}) {
  return spawn(cmd, args, { stdio: 'inherit', shell: true, cwd: ROOT, ...opts })
}

function waitForPort(port, timeoutMs = 90_000) {
  return new Promise((resolve, reject) => {
    const deadline = Date.now() + timeoutMs
    function attempt() {
      const sock = createConnection(port, '127.0.0.1')
      sock.on('connect', () => { sock.destroy(); resolve() })
      sock.on('error', () => {
        sock.destroy()
        if (Date.now() > deadline) {
          reject(new Error(`Port ${port} not available after ${timeoutMs}ms`))
        } else {
          setTimeout(attempt, 1000)
        }
      })
    }
    attempt()
  })
}

function runToCompletion(cmd, args) {
  return new Promise((resolve) => {
    const p = run(cmd, args)
    p.on('exit', (code) => resolve(code ?? 0))
  })
}

// ── main ──────────────────────────────────────────────────────────────────────

console.log('==> Starting Firebase emulators (auth, firestore)')
const emulators = run('pnpm', ['exec', 'firebase', 'emulators:start',
  '--only', 'auth,firestore', '--project', 'demo-lineup'])

// Kill emulators when this process exits
function cleanup() {
  try { emulators.kill() } catch {}
}
process.on('exit', cleanup)
process.on('SIGINT', () => process.exit(0))
process.on('SIGTERM', () => process.exit(0))

;(async () => {
  console.log('==> Waiting for Firestore emulator on :8080')
  await waitForPort(8080)
  console.log('==> Waiting for Auth emulator on :9099')
  await waitForPort(9099)
  console.log('    emulators up')

  console.log('==> Seeding emulator data')
  const seedCode = await runToCompletion('pnpm', ['seed'])
  if (seedCode !== 0) console.log('    seed failed (continuing anyway)')

  console.log('==> Starting Next.js dev server on :3000')
  const web = run('pnpm', ['dev:web'])
  web.on('exit', () => process.exit(0))
})().catch((err) => {
  console.error('dev-local error:', err.message)
  process.exit(1)
})
