#!/usr/bin/env bash
# Generates apps/web/.env.local pointing the web app at the Firebase emulators.
# Called by .devcontainer/setup.sh and scripts/dev.sh — safe to run repeatedly.
set -euo pipefail

# Resolve repo root so this works regardless of the caller's cwd.
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT/apps/web/.env.local"

cat > "$ENV_FILE" <<'EOF'
# Auto-generated by scripts/write-env-local.sh — do not edit by hand.
# Points the web app at the local Firebase emulators (demo-linyup project).
NEXT_PUBLIC_USE_EMULATORS=true
NEXT_PUBLIC_FIREBASE_API_KEY=demo-api-key
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=demo-linyup.firebaseapp.com
NEXT_PUBLIC_FIREBASE_DATABASE_URL=https://demo-linyup.firebaseio.com
NEXT_PUBLIC_FIREBASE_PROJECT_ID=demo-linyup
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=demo-linyup.appspot.com
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=000000000000
NEXT_PUBLIC_FIREBASE_APP_ID=1:000000000000:web:0000000000000000000000
EOF

# In a Codespace the emulators are reached via HTTPS port-forwarding, not
# localhost. Expose the codespace name + domain so the browser SDK can build
# the forwarded emulator URLs (<codespace>-<port>.<domain>).
if [ -n "${CODESPACE_NAME:-}" ] && [ -n "${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN:-}" ]; then
  {
    echo "NEXT_PUBLIC_CODESPACE_NAME=${CODESPACE_NAME}"
    echo "NEXT_PUBLIC_CODESPACE_DOMAIN=${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"
  } >> "$ENV_FILE"
  echo "    wrote apps/web/.env.local (Codespaces mode)"
else
  echo "    wrote apps/web/.env.local (localhost mode)"
fi
